name: OpenTK GLFW Redistributable

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix: 
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Install dependencies
      run: ./download_dependencies.ps1
      shell: pwsh
    - name: Create Nuget Package
      run: ./make_nuget.ps1
      shell: pwsh
    - name: Deploy Nuget Package
      run: dotnet nuget push ./artifacts/*.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
